# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

# NOTE: The python version will use the .NET Api and WebApp projects until the python versions are done.
version: "3.8"

services:
  azsdkdemonetwebapp:
    image: jongio/azsdkdemonetwebapp
    build:
      context: ../net
      dockerfile: WebApp/Dockerfile
    depends_on:
      - azsdkdemonetapi
    ports:
      - 1080:80
      - 1443:443
  azsdkdemonetapi:
    image: jongio/azsdkdemonetapi
    env_file: ../../.env
    volumes: 
        - "${HOME}/.azure:/root/.azure"
    build:
      context: ../net
      dockerfile: Api/Dockerfile
    ports:
      - 2080:80
      - 2443:443
  azsdkdemopythonqueueservice:
    image: jongio/azsdkdemopythonqueueservice
    env_file: ../../.env
    volumes:
      - ${HOME}/.azure:/root/.azure
    build:
      context: .
      dockerfile: services/queue-service/Dockerfile